### PR TITLE
fix: Only require twilio_webhook_authentication if Rack version > 2

### LINKED ISSUE #605: Upgrading from 5.40.1 to 5.66.2 raises a `LoadError: cannot load such file -- rack/media_type` error
### Issue Summary
I'm upgrading twilio-ruby from 5.40.1 to 5.66.2 and getting the following error:

```
LoadError:
  cannot load such file -- rack/media_type
# /Users/jasonnoble/.rvm/gems/ruby-2.7.5@rails4.2.11/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/jasonnoble/.rvm/gems/ruby-2.7.5@rails4.2.11/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
# /Users/jasonnoble/.rvm/gems/ruby-2.7.5@rails4.2.11/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
# /Users/jasonnoble/.rvm/gems/ruby-2.7.5@rails4.2.11/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/jasonnoble/.rvm/gems/ruby-2.7.5@rails4.2.11/gems/twilio-ruby-5.66.2/lib/rack/twilio_webhook_authentication.rb:3:in `<top (required)>'
# /Users/jasonnoble/.rvm/gems/ruby-2.7.5@rails4.2.11/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/jasonnoble/.rvm/gems/ruby-2.7.5@rails4.2.11/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
# /Users/jasonnoble/.rvm/gems/ruby-2.7.5@rails4.2.11/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
# /Users/jasonnoble/.rvm/gems/ruby-2.7.5@rails4.2.11/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/jasonnoble/.rvm/gems/ruby-2.7.5@rails4.2.11/gems/twilio-ruby-5.66.2/lib/twilio-ruby.rb:13:in `<top (required)>'
# /Users/jasonnoble/.rvm/gems/ruby-2.7.5@rails4.2.11/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
# ./config/application.rb:13:in `<top (required)>'
```

It appears that this was fixed in #602 via `require 'rack/twilio_webhook_authentication' if defined?(Rack)`.  However, the `rack/media_type` is only available in rack v2 and later (I'm on rack-1.6.13).

Proposed fix:
```
# lib/twilio-ruby.rb:13
require 'rack/twilio_webhook_authentication' if defined?(Rack) && (Gem.loaded_specs["rack"].version > Gem::Version.new("2"))
```

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce

```
# Gemfile
source 'https://rubygems.org'

ruby '2.7.5'

gem 'rack', '< 2'
gem 'twilio-ruby'
```

After running `bundle install`, open an `irb` session:

```
2.7.5 :001 > require 'rack'
 => true
2.7.5 :002 > require 'twilio-ruby'
Traceback (most recent call last):
       13: from /Users/jasonnoble/.rvm/rubies/ruby-2.7.5/bin/irb:23:in `<main>'
       12: from /Users/jasonnoble/.rvm/rubies/ruby-2.7.5/bin/irb:23:in `load'
       11: from /Users/jasonnoble/.rvm/rubies/ruby-2.7.5/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
       10: from (irb):2
        9: from /Users/jasonnoble/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
        8: from /Users/jasonnoble/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
        7: from /Users/jasonnoble/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
        6: from /Users/jasonnoble/.rvm/gems/ruby-2.7.5@twilio/gems/twilio-ruby-5.66.2/lib/twilio-ruby.rb:13:in `<top (required)>'
        5: from /Users/jasonnoble/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
        4: from /Users/jasonnoble/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
        3: from /Users/jasonnoble/.rvm/gems/ruby-2.7.5@twilio/gems/twilio-ruby-5.66.2/lib/rack/twilio_webhook_authentication.rb:3:in `<top (required)>'
        2: from /Users/jasonnoble/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146:in `require'
        1: from /Users/jasonnoble/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146:in `require'
LoadError (cannot load such file -- rack/media_type)
2.7.5 :003 >
```

### Technical details:
* twilio-ruby version: 5.66.2
* ruby version: 2.7.5, 2.6.6

### PR DESCRIPTION
**Pull request by jasonnoble**
Fixes #605 

# Fixes #

Only require the twilio_webhook_authentication functionality if the Rack version is > 2.

FYI, #602 attempted to fix this, but doesn't work when the Rack version is < 2.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-ruby/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

### CODE REVIEW

**Comment by jasonnoble** [comment]
I'm more than willing to add tests/documentation if you feel it's required.  Pretty small change IMO.

File: lib/twilio-ruby.rb [hunk 1]
```diff
@@ -10,7 +10,7 @@
 require 'json'
 
 require 'twilio-ruby/version' unless defined?(Twilio::VERSION)
-require 'rack/twilio_webhook_authentication' if defined?(Rack)
+require 'rack/twilio_webhook_authentication' if defined?(Rack) && (Gem.loaded_specs["rack"].version > Gem::Version.new("2"))
```
Comment (childish-sambino) [inline lib/twilio-ruby.rb:13]: Think this can be made more specific if we include `Rack::MediaType` as the needed depdendency (since that's what's required in `twilio_webhook_authentication`). E.g.,
```
require 'rack/twilio_webhook_authentication' if defined?(Rack) && defined?(Rack::MediaType)
```

Comment (jasonnoble) [reply lib/twilio-ruby.rb]: Done.

**Review by childish-sambino — APPROVED** [review]
