### PR TITLE
fix: avoid JSON::ParserError for all server errors

### LINKED ISSUE #544: 504 Gateway Time-out caused a JSON::ParserError
### Issue Summary

Given Twilio API sometimes return `504 Gateway Time-out` with HTML response body, the Ruby client should not try to parse the response payload as JSON. 

Some Twilio::REST::RestError is expected instead. 

### Steps to Reproduce
It occurred with the following API request:
```ruby
@client = Twilio::REST::Client.new
@client.messages.create(
      messaging_service_sid: ENV['TWILIO_MESSAGING_SERVICE_SID'],
      to: to,
      body: message)
```

### Exception/Log
```
JSON::ParserError: 784: unexpected token at '<html> 
<head><title>504 Gateway Time-out</title></head> 
<body> 
<center><h1>504 Gateway Time-out</h1></center> 
<hr><center>openresty</center> 
</body> 
</html> 
'
- 11 non-project frames
1 File "/app/vendor/bundle/ruby/2.7.0/gems/json-2.3.1/lib/json/common.rb" line 263 in parse
2 File "/app/vendor/bundle/ruby/2.7.0/gems/json-2.3.1/lib/json/common.rb" line 263 in parse
3 File "/app/vendor/bundle/ruby/2.7.0/gems/twilio-ruby-5.39.2/lib/twilio-ruby/framework/response.rb" line 10 in initialize
4 File "/app/vendor/bundle/ruby/2.7.0/gems/twilio-ruby-5.39.2/lib/twilio-ruby/http/http_client.rb" line 43 in new
5 File "/app/vendor/bundle/ruby/2.7.0/gems/twilio-ruby-5.39.2/lib/twilio-ruby/http/http_client.rb" line 43 in _request
6 File "/app/vendor/bundle/ruby/2.7.0/gems/twilio-ruby-5.39.2/lib/twilio-ruby/http/http_client.rb" line 59 in request
7 File "/app/vendor/bundle/ruby/2.7.0/gems/twilio-ruby-5.39.2/lib/twilio-ruby/rest/client.rb" line 82 in request
8 File "/app/vendor/bundle/ruby/2.7.0/gems/twilio-ruby-5.39.2/lib/twilio-ruby/framework/domain.rb" line 22 in request
9 File "/app/vendor/bundle/ruby/2.7.0/gems/twilio-ruby-5.39.2/lib/twilio-ruby/framework/version.rb" line 53 in request
10 File "/app/vendor/bundle/ruby/2.7.0/gems/twilio-ruby-5.39.2/lib/twilio-ruby/framework/version.rb" line 147 in create
11 File "/app/vendor/bundle/ruby/2.7.0/gems/twilio-ruby-5.39.2/lib/twilio-ruby/rest/api/v2010/account/message.rb" line 124 in create
```

### Technical details:
* twilio-ruby version: 5.39.2
* ruby version: 2.7.0

### PR DESCRIPTION
**Pull request by dan-jensen**
When there is a Twilio service outage that causes the Twilio API to
return a 503 Service Unavailable error, a JSON::ParserError is
raised. This fixes that bug by detecting all 5XX server error status
codes, and handling them the same way 504 status codes were already
being handled.

This is related to the [existing bug issue](https://github.com/twilio/twilio-ruby/issues/544#issuecomment-991285018) and is basically an expansion of a [previous pull request](https://github.com/twilio/twilio-ruby/pull/554).

Fixes #544

A short description of what this PR does.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-ruby/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation about the functionality in the appropriate .md file
- [x] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

### CODE REVIEW

**Comment by dan-jensen** [comment]
Note: I was tempted to implement the same change for client errors by changing `elsif response.status == 400` to use `Faraday::Response::RaiseError::ClientErrorStatuses`.  But that felt like too big a change for this PR.

Also, it makes me nervous that line appears _after_ `elsif response.body && !response.body.empty?`.  I would think we should check for both client errors and server errors _before_ we return the response body, so I'm a bit wary of some special intent there.  But if I had to guess, I would say it was an unintentional oversight in the [original implementation](https://github.com/twilio/twilio-ruby/commit/20a6bb734fc01ae7318c0f1914ed2b4d89cf94ee).  I would recommend a follow-up PR to handle client errors.

**Comment by dan-jensen** [comment]
@eshanholtz would you have time to review this?  Pinging you because you merged a [similar PR earlier this year](https://github.com/twilio/twilio-ruby/pull/554) so I'm guessing you have the most context awareness 🙂

File: lib/twilio-ruby/http/http_client.rb [hunk 1]
```diff
@@ -44,8 +44,8 @@ def _request(request)
         @last_response = nil
 
         response = send(request)
-        if response.status == 504
-          object = { message: 'Request timeout', code: 504 }.to_json
+        if Faraday::Response::RaiseError::ServerErrorStatuses.include?(response.status)
```
Comment (januszm) [inline lib/twilio-ruby/http/http_client.rb:47]: `ServerErrorStatuses` is just a range `(500..600)`, perhaps you could use it here directly instead of referencing the class with its namespace from Faraday's  `RaiseError` ?

```ruby
if (500.600).include?(response.status)
```

Comment (dan-jensen) [reply lib/twilio-ruby/http/http_client.rb]: @januszm you're definitely right, I just replaced the Faraday dependency with `500..599` 👍

**Comment by doryphores** [comment]
Hello. Any movement on this? Feels like a good fix to merge in.

**Review by childish-sambino — APPROVED** [review]
LGTM
