### PR TITLE
breaking: Catch and wrap Faraday client errors

### LINKED ISSUE #455: Unhandled Faraday::Connection Failed
**Version:**

5.24.0 and 5.25.0

Ruby 2.4.4 and 2.6.2

### Code Snippet
```ruby
message.fetch
```

### Exception/Log

fetch code

https://github.com/twilio/twilio-ruby/blob/5.24.0/lib/twilio-ruby/rest/api/v2010/account/message.rb#L316-L328

exception

```
"#<Faraday::ConnectionFailed wrapped=#<Net::OpenTimeout: execution expired>>"
exception_class=>"Faraday::ConnectionFailed", :exception_details=>{:type=>"Faraday::ConnectionFailed", :message=>"execution expired", :backtrace=>"

Faraday::ConnectionFailed: execution expired
Net::OpenTimeout: execution expired
```

backtrace

```
"/app/vendor/ruby-2.6.2/lib/ruby/2.6.0/net/http.rb" line 947 in initialize
"/app/vendor/ruby-2.6.2/lib/ruby/2.6.0/net/http.rb" line 947 in open
"/app/vendor/ruby-2.6.2/lib/ruby/2.6.0/net/http.rb" line 947 in block in connect
"/app/vendor/ruby-2.6.2/lib/ruby/2.6.0/timeout.rb" line 103 in timeout
"/app/vendor/ruby-2.6.2/lib/ruby/2.6.0/net/http.rb" line 945 in connect
"/app/vendor/ruby-2.6.2/lib/ruby/2.6.0/net/http.rb" line 930 in do_start
"/app/vendor/ruby-2.6.2/lib/ruby/2.6.0/net/http.rb" line 919 in start
"/app/vendor/ruby-2.6.2/lib/ruby/2.6.0/net/http.rb" line 1470 in request
"/app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.1/lib/scout_apm/instruments/net_http.rb" line 30 in block in request_with_scout_instruments
"/app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.1/lib/scout_apm/tracer.rb" line 34 in instrument
"/app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.1/lib/scout_apm/tracer.rb" line 44 in instrument
"/app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.1/lib/scout_apm/instruments/net_http.rb" line 29 in request_with_scout_instruments
"/app/vendor/ruby-2.6.2/lib/ruby/2.6.0/net/http.rb" line 1228 in get
"/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb" line 85 in perform_request
"/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb" line 43 in block in call
"/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb" line 92 in with_net_http_connection
"/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb" line 38 in call
"/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/request/url_encoded.rb" line 15 in call
"/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb" line 143 in build_response
"/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb" line 387 in run_request
"/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb" line 138 in get
"/app/vendor/bundle/ruby/2.6.0/gems/twilio-ruby-5.25.0/lib/twilio-ruby/http/http_client.rb" line 38 in _request
"/app/vendor/bundle/ruby/2.6.0/gems/twilio-ruby-5.25.0/lib/twilio-ruby/http/http_client.rb" line 56 in request
"/app/vendor/bundle/ruby/2.6.0/gems/twilio-ruby-5.25.0/lib/twilio-ruby/rest/client.rb" line 81 in request
"/app/vendor/bundle/ruby/2.6.0/gems/twilio-ruby-5.25.0/lib/twilio-ruby/framework/domain.rb" line 22 in request
"/app/vendor/bundle/ruby/2.6.0/gems/twilio-ruby-5.25.0/lib/twilio-ruby/framework/version.rb" line 53 in request
"/app/vendor/bundle/ruby/2.6.0/gems/twilio-ruby-5.25.0/lib/twilio-ruby/framework/version.rb" line 61 in fetch
"/app/vendor/bundle/ruby/2.6.0/gems/twilio-ruby-5.25.0/lib/twilio-ruby/rest/api/v2010/account/message.rb" line 321 in fetch
"/app/vendor/bundle/ruby/2.6.0/gems/twilio-ruby-5.25.0/lib/twilio-ruby/rest/api/v2010/account/message.rb" line 581 in fetch
```

### Steps to Reproduce
1.
2.
3.

### Proposal

Should be handled, I think, by `Twilio::REST::RestError`, probably in https://github.com/twilio/twilio-ruby/blob/08f1ba2f042eeefb29f19f7dd13add40c4117ac9/lib/twilio-ruby/http/http_client.rb

It's not noted in the guide as a possible error to be raised nor in the docs https://github.com/twilio/twilio-ruby/blob/5.25.0/lib/twilio-ruby/rest/api/v2010/account/message.rb#L316-L328

https://github.com/twilio/twilio-ruby/wiki/Ruby-Version-5.x-Upgrade-Guide

### PR DESCRIPTION
**Pull request by childish-sambino**
Fixes #455 

Please ensure the following steps have been run before submitting this pull request:

- [x] Run `make test` and ensure it passes locally
- [x] Run `make lint` to appease Rubocop

### CODE REVIEW

File: lib/twilio-ruby/http/http_client.rb [hunk 1]
```diff
@@ -52,6 +50,14 @@ def _request(request)
         twilio_response
       end
 
+      def send(request)
+        @connection.send(request.method.downcase.to_sym,
+                         request.url,
+                         request.method == 'GET' ? request.params : request.data)
+      rescue Faraday::ClientError => e
+        raise Twilio::REST::TwilioError, e
```
Comment (bf4) [inline lib/twilio-ruby/http/http_client.rb]: fwiw, the way I handled this was

```ruby
  rescue Faraday::ConnectionFailed => e
    # NOTE(BF): see https://github.com/twilio/twilio-ruby/issues/455
    message = "#{e.class.name} #{e.message}"
    error = Twilio::REST::TwilioError.exception(message)
    error.set_backtrace e.backtrace
    raise error
```

Comment (childish-sambino) [reply lib/twilio-ruby/http/http_client.rb]: Changing to a _breaking_ change since `Faraday::ConnectionFailed` errors are no longer leaked which may break existing error handling.

Since the original error is contained in the wrapper error `cause` field, I don't think it's necessary to modify the message and backtrace.

**Comment by childish-sambino** [comment]
@thinkingserious Docs updated.
